### ISSUE TITLE
incompatibility with mask command line runner

### ISSUE THREAD

**Issue by bachrc** [pvolok/mprocs#106]
when i use mprocs to run multiple [mask](https://github.com/jacobdeichert/mask) commands, mprocs does not end processes. whatever the signal i give.

it seems that because mask is in the middle, that the children PIDs are not handled by mprocs when terminating. do you know how to handle this? thanks in advance

**Comment by pvolok** [comment]
You can try to send Ctrl-C as a stop command. Most likely `mask` will handle it and terminate all the processes it spawned. Here is how you can do it:

```
procs:
  my-process:
    cmd: ["mask"]
    stop: { send-keys: ["<C-c>"] }
```
