### ISSUE TITLE
[feature] Option to highlight (background/foreground) of the output and keep track of some specific highlights (bookmarks)

### ISSUE THREAD

**Issue by ddofborg** [pvolok/mprocs#109]
I use `mprocs` to run background taks based on a producer / consumer queue (basically run forever). Very simple and effective tool, love it!!

It's helpful to be able to quickly find if some output contains a string which indicates something, like an error or some other message. Highlighting the output and keeping track a list (bookmarks) of these matches would be super helpful. 

Example: highlight the output with `color C` if `regex R` matches a line. Then keep track of the position of this line in the scrol buffer and keep a list of matches (bookmarks) for quick navigation to the match. Also `clearing of the bookmarks` and keeping at most `X recent bookmarks` might be useful. Other option would be to keep a `relative time` or `timestamp` of each bookmark. Also an option to highlight the whole line or just the match.

```yaml
procs:
  proc1:
    shell: "./start.sh"
    highlights:
      - regex: "^err:"
        bg: "red"
        bookmark: true
        highlight: line
      - regex: "^ok:"
        fg: green
        bookmark: false
        highlight: match
```
