### ISSUE TITLE
Add priority to commands

### ISSUE THREAD

**Issue by ricardofabila** [pvolok/mprocs#123]
Would be very cool if you could also add a priority int proprty to the commands for example if you use it for let's say a rails app or something. You may need to start the docker db and redis db before launching sidekiq and the rails server.

It would look something like this:

```yaml
procs:
  rails:
    cmd: ["rails", "server", "--port", "3000"]
    cwd: "/Users/ricardofabilareyes/projects/backend"
    priority: 1
  sidekiq:
    cmd: ["bundle", "exec", "sidekiq", "-C", "config/sidekiq.yml"]
    cwd: "/Users/ricardofabilareyes/projects/backend"
    priority: 1
  database:
    cmd: ["docker", "start", "mento_db"]
    priority: 2
  redis:
    cmd: ["docker", "start", "redis-stack"]
    priority: 2
```

This way both **database** and **redis** would start before **rails** and **sidekiq**.

I love this program man, I even added it to my own [pkg manager](https://www.getfox.sh/) 😄
