### ISSUE TITLE
mprocs 0.7.0-rc1 throws `Error: invalid type: map, expected a Value::Tagged enum` when `stop` uses `send-keys` on Windows

### ISSUE THREAD

**Issue by NikGovorov** [pvolok/mprocs#139]
Here is the sample config to reproduce the issue:
```yaml
procs:
  dev:
    shell: 'npm run dev'
    stop:
      send-keys:
        - <C-c>
```
The issue is specific to the Windows operating system. I tried to narrow down the particular commit that triggered the problem, however, the Windows build already had issues right after the release of v0.6.4. I suspect that the update of `serde/serde_yaml`  may have caused the problem, but I am not entirely certain.
