### ISSUE TITLE
Dependencies between processes

### ISSUE THREAD

**Issue by clotodex** [pvolok/mprocs#158]
I need my compilation or client to wait for a database or service to be responsive and up, otherwise it fails.

This has been indirectly talked about over a year ago in #123 and #95.

I would love to switch from https://github.com/F1bonacc1/process-compose, but this is blocking me.

A "relatively" simple gate that works like "poll until this command returns positive" could do the trick.
Process compose has a readyness probe you define for a process A and then B can wait for A to be ready.
Another potentially simpler way of doing it would be to define blockers for B directly, by a http code or exit code of a shell, etc.

Example of client server
```
procs:
  client:
    cmd: ["python client.py"]
    wait_http: "localhost:8080/v1/ready",
  server:
    shell: "nodemon server.js"
```

What do you think?

**Comment by nothingnesses** [comment]
@pvolok I also would like a dependency management system to be implemented for mprocs. Here are my thoughts on how it could function/be implemented:

For each dependent process, we'd need to add ways to:
* Define dependency processes.
* Define a command to be ran to check if this dependent process should be ran. This command would likely need to be given context/data about the dependency process. I think we can make do with simply providing the dependency process' PID, exit status and exit signal (along with indication of whether these are `Some` or `None`) as arguments to the checker command to be ran. But if you think we need to pass in additional data/context, we could instead do so in the form of a more structured data interchange format such as JSON. I think environment variables set in a dependency process should also, at minimum, be available to the checker command of a dependent process.
* Define the frequency with which the checker command above should be ran. This could have a default value for convenience.

The UI to define dependencies could be something like:

```yaml
procs:
  a:
    shell: 'yes'
  b:
    shell: 'sleep 60'
  c:
    env:
      C_OUT_FILE: '$(mktemp)'
    shell: 'sleep 30; echo 'foobar' > "${C_OUT_FILE}"'
  d:
    shell: 'echo foo'
    depends:
      a:
        shell: 'test "${1}" = "Some:*" && test "${2}" = "None"'
        freq: 1 # in Hz, optional, maybe 1 by default
      b:
        shell: 'test "${3}" = "Some:*" && test "${3##*:}" = "SIGKILL"'
      c:
        shell: 'test "$(cat ${C_OUT_FILE})" = "foobar"'
```

In the above example, the commands in `procs.d.depends.a.shell`, `procs.d.depends.b.shell`, `procs.d.depends.c.shell` will be ran once every second, until process "d" has been ran, with the PIDs, exit statuses and exit signals passed into them as `$1`, `$2` and `$3` from the commands in processes "a", "b" and "c", respectively. Process "d" should be ran only if the arguments passed into the checker commands for "a", "b" and "c" are something like the following:

```csv
process, pid ($1), exit status ($2), exit signal ($3)
a,       Some:999, None,             None
b,       None,     137,              Some:SIGKILL
c,       None,     0,                None
```

Eventually, it might be nice to have some form of dependency chain validation. To do this, during setup, after processes have been added, for each process, we could check its dependency chains to ensure these don't contain the current process. If they do, this indicates a cycle and mprocs should probably exit with an error message.

### Questions

* Aside from PID, exit status and exit signal of dependency processes, what other data do we need to pass in to the checker commands?
* Should environment variables of a dependency process also be available to dependent processes (not just to their checker commands)?
* How should this system work with duplicate processes? Do we maybe need to pass in some kind of "duplicate ID" to the processes to determine which duplicate process we are working with and be able to differentiate between them? This could be useful in case we need to write to a file whose name is dependent on the duplicate ID.
* Is the proposed solution of passing in different parameters as arguments to the checker command sufficient, or would it be better just to pass in a single argument as something like JSON (and just have the user parse this using e.g., `jq`), which would allow us to extend it in the future, in case we need to pass in more things later on?

**Comment by nothingnesses** [comment]
Thinking back on my previous proposed solution, I think the UI/UX could be simplified further by removing idea of passing in arguments to the checker commands and instead simply relying solely on passing data through file contents and environment variables.

Here's what an example mprocs.yaml for that might look like:

```yaml
procs:
  # Dependency process that needs to write some output to file
  a:
    env:
      TMP: '/tmp/tmp.a'
    shell: 'sleep 30; echo "foobar" > "${TMP}"'
  # Dependency process that needs to finish successfully first
  b:
    env:
      TMP: '/tmp/tmp.b'
    shell: 'sleep 30; echo $? > "${TMP}"'
  c:
    depends:
      # Only run "c" if "a" has written its output
      a: 'until test "$(cat ${TMP})" = "foobar"; do sleep 1; done;'
      # Only run "c" if "b" has finished sucessfully
      b: 'until test "$(cat ${TMP})" -eq 0; do sleep 1; done;'
    shell: 'echo foo'
```
