### ISSUE TITLE
Feature request: Integrate watchexec

### ISSUE THREAD

**Issue by emosenkis** [pvolok/mprocs#163]
Thanks for mprocs! It's a great tool and I'm not aware of anything else like it.

I'm using it to run several server processes that need to be restarted when the code changes. To do that, I'm running several instances of watchexec inside of mprocs and it works, but it was quite difficult to figure out a combination of mprocs + watchexec configuration that would actually allow mprocs to kill watchexec+server and exit (most combinations would either hang, with only the server killed but watchexec still running or would exit with watchexec killed but the server still running (this is exacerbated by the fact that the servers themselves fork several workers and can only be killed by delivering a certain signal, which isn't even the same across different servers).

It would be awesome if mprocs could integrate the watchexec library so this could all be handled in a single mprocs process, and I think it would make a great addition to mprocs.

**Comment by senekor** [comment]
I immediately thought of this when first hearing about mprocs. "Can it also replace watchexec?" I often need to wire up several instances of watchexec for different tasks per project... These functionalities would be awesome if combined in a single tool IMO.

**Comment by pvolok** [comment]
I certainly would like to have this feature.

**Comment by tammersaleh** [comment]
Hilariously, Claude hallucinated that mprocs supported a `watch` subcommand. For what it's worth, here's the format it gave:

``` yaml
procs:
  tests:
    cmd: ["bundle", "exec", "rake", "test"]
    watch:
      paths: ["lib/**/*.rb", "test/**/*.rb"]
      debounce: 500  # Wait 500ms after last change before restarting
```
