### ISSUE TITLE
Custom Key Bindings

### ISSUE THREAD

**Issue by kimreyio** [pvolok/mprocs#19]
Would it be possible to add custom key bindings? I'd love a modifier+left/right arrow to navigate back and forth between the list and the process if not.

**Comment by pvolok** [comment]
Yes. This is in fact the next thing on my list. I will report progress in this issue.

**Comment by pvolok** [comment]
Just released mprocs 0.4.0 with key bindings support.
Docs: https://github.com/pvolok/mprocs#keymap
List of supported command: https://github.com/pvolok/mprocs#remote-control

**Comment by dreamcat4** [comment]
is there a reference somewhere for other keybinds syntax which are not specified in the readme file? For example what if i want to bind commands to `ctrl + tab`, and `ctrl + shift + tab` ?

**Comment by pvolok** [comment]
@dreamcat4 The docs for the key syntax are still missing. For your examples: `<C-Tab>` and `<C-S-Tab>`.

**Comment by dreamcat4** [comment]
@pvolok have you tried `<C-Tab>` and `<C-S-Tab>` on your system? Because when I tried them yesterday (before leaving that previous comment). They didn't work (for me). And this morning they it doesn't work. So if they are supposed to be the correct bindings then maybe something else is wrong?


Heres my full `mprocs.yaml` file:

```yaml

procs:
  bash: "bash"
  # htop: "htop"
  # ssh tomato:
    # shell: "ssh tomato"
    # env:
      # NODE_ENV: test
  .config/mprocs:
    shell: "cd ~/.config/mprocs && micro *"

# keys when process list is focused
keymap_procs:
  <C-Tab>: { c: toggle-focus }
  <C-S-Tab>: { c: toggle-focus }
  <C-a>: null # unbind key

# keys when terminal is focused
keymap_term:
  reset: true
  <C-q>: { c: toggle-focus }
  <C-j>:
    c: batch
    cmds:
      - { c: focus-procs }
      - { c: next-proc }


```
