### ISSUE TITLE
[Feature request] Option to not auto-run the process on startup

### ISSUE THREAD

**Issue by serhez** [pvolok/mprocs#32]
As per in the title, it would be nice if the processes did not run automatically on `mprocs`'s startup, but had to be run manually.

**Comment by pvolok** [comment]
Sure thing. I will add it in the next version.

**Comment by pvolok** [comment]
mprocs 0.5.0 adds an `autostart` option:
```yaml
procs:
  bash:
    shell: bash
    autostart: false
```
