### ISSUE TITLE
mprocs doesn't respect config file

### ISSUE THREAD

**Issue by thisismygitrepo** [pvolok/mprocs#69]
As per README

`C:\Users\alex\AppData\Roaming\mprocs\mprocs.yaml`

is a global config file that will be loaded in absence of passed or a local file, but that is not happening on my machine.

**Comment by pvolok** [comment]
Are you trying to define `procs` in your global config file? Global config file allows all config fields except `procs`.

**Comment by thisismygitrepo** [comment]
I just remved `procs` and deindented the rest of the of field, still no game.

```

explorer:
  shell:
    $select: os
    windows: "lf"
    $else: "lf"
  env:
    TEXT:
      $select: os
      windows: Windows
      linux: Linux
      macos: Macos
      freebsd: FreeBSD

```
